/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-05-09 06:02:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sampleServiceProxy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Method_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>Methods</TITLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY>\r\n");
      out.write("<H1>Methods</H1>\r\n");
      out.write("<UL>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=2\" TARGET=\"inputs\"> getEndpoint()</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=5\" TARGET=\"inputs\"> setEndpoint(java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=10\" TARGET=\"inputs\"> getService()</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=13\" TARGET=\"inputs\"> getUserId(java.lang.String,java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=20\" TARGET=\"inputs\"> signUp(java.lang.String,java.lang.String,java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=29\" TARGET=\"inputs\"> getUserNameById(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=34\" TARGET=\"inputs\"> signIn(java.lang.String,java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=41\" TARGET=\"inputs\"> insertEducation(java.lang.String,java.lang.String,java.lang.String,int,java.lang.String,int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=56\" TARGET=\"inputs\"> insertExperience(java.lang.String,int,java.lang.String,java.lang.String,java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=69\" TARGET=\"inputs\"> insertSummary(java.lang.String,int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=76\" TARGET=\"inputs\"> insertSkills(java.lang.String,int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=83\" TARGET=\"inputs\"> getEducationById(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=106\" TARGET=\"inputs\"> getSummaryById(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=125\" TARGET=\"inputs\"> getSkillsById(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=136\" TARGET=\"inputs\"> getAllUsers(java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=141\" TARGET=\"inputs\"> getUserIdByName(java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=146\" TARGET=\"inputs\"> sendInvitations(int,int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=153\" TARGET=\"inputs\"> getConnectionID(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=158\" TARGET=\"inputs\"> getMD5(java.lang.String)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=163\" TARGET=\"inputs\"> getExperienceById(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=180\" TARGET=\"inputs\"> displayInvitation(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=185\" TARGET=\"inputs\"> acceptInvitations(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=190\" TARGET=\"inputs\"> rejectInvitations(int)</A></LI>\r\n");
      out.write("<LI><A HREF=\"Input.jsp?method=195\" TARGET=\"inputs\"> displayConnections(int)</A></LI>\r\n");
      out.write("</UL>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
