/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-05-05 08:37:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\"> \n");
      out.write("<style>\n");
      out.write("p{\n");
      out.write("    color:black;\n");
      out.write("    font-family:Arial;\n");
      out.write("    font-size:50;\n");
      out.write("    margin-left: 120px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write(" \n");
      out.write("<title>LinkedIn</title>  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<nav style=\"padding-bottom: 10px;box-shadow: 3px 3px 5px #888888; background-color: #F5F5F5;\">\n");
      out.write("\n");
      out.write(" \n");
      out.write("<form id=\"form2\" method=\"post\" action=\"signin\">\n");
      out.write("<fieldset style=\"width: 800px\">  \n");
      out.write("                <table>  \n");
      out.write("                <tr>  \n");
      out.write("               <td> <img src=\"../resources/images/linkedin2.jpg\" alt=\"LinkedIn\" style=\"margin-left:-20px; margin-top: 5px;width:90px;height:40px\"></td>\n");
      out.write("                    <td>Email Address</td> \n");
      out.write("                    <td><input type=\"text\" name=\"username\" required=\"required\" style=\"margin-left: 10px;\"/></td>  \n");
      out.write("                  \n");
      out.write("                    <td> Password</td>\n");
      out.write("                    <td><input type=\"password\" name=\"password\" required=\"required\" style=\"margin-left: 10px;\"/></td>  \n");
      out.write("                         \n");
      out.write("                    <td><input type=\"submit\" value=\"Sign In\" style=\"margin-left: 100px;\"/></td> \n");
      out.write("                     <td><input type =\"hidden\" name=\"userid\" value=\"");
      out.print(request.getParameter("userid"));
      out.write("\"/></td>  \n");
      out.write("                </tr>  \n");
      out.write("            </table>  \n");
      out.write("        </fieldset>  \n");
      out.write("\t<!-- <div class=\"form-row\"><span class=\"label\">Username </span><input type=\"text\" name=\"username\"/></div>\n");
      out.write("\t<div class=\"form-row\"><span class=\"label\">Password </span><input type=\"password\" name=\"password\"/></div>\n");
      out.write("\t<div class=\"form-row\"><input class=\"submit\" type=\"submit\" value=\"submit\"/></div> -->\n");
      out.write("</form>\n");
      out.write("</nav>\n");
      out.write(" \n");
      out.write("<h1 style=\"margin-left: 100px; font-size: 35px; margin-bottom:100px;\">Connect, share ideas, and discover opportunities.</h1> \n");
      out.write("   <div>\n");
      out.write("   <form id=\"form1\" method=\"post\" action=\"signup\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th rowspan = \"7\">\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img1.png\" width=\"150\" height=\"150\" alt=\"Male Headshot\">\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img2.png\" width=\"150\" height=\"150\" alt=\"Female Headshot\">\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img3.png\" width=\"150\" height=\"150\" alt=\"Male Headshot\"><br> <br>\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img4.png\" width=\"150\" height=\"150\" alt=\"Male Headshot\">\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img5.png\" width=\"150\" height=\"150\" alt=\"Male Headshot\">\n");
      out.write("\t\t\t\t\t\t<img src=\"../resources/images/img6.png\" width=\"150\" height=\"150\" alt=\"Male Headshot\">\n");
      out.write("\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<h2 style=\"margin-top:1px;margin-left:400px;width: 400px;\">Get Started - it's free.</h2>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<h4 style=\"margin-top:1px;margin-left:400px;width: 400px;\">Registration takes less than 2 minutes.</h4>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\">\t\t\t\t \n");
      out.write("\t\t\t\t        <input   type=\"text\" placeholder=\"First Name\" name=\"first\" required =\"required\" style=\"margin-top: 15px;margin-left: -400px;width: 200px;\" >\n");
      out.write("\t\t\t\t   \t\t</div>\n");
      out.write("\t\t\t\t   \t\t\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-sm-2\">\t\t\t\t \n");
      out.write("\t\t\t\t        <input   type=\"text\" placeholder=\"Last Name\" name=\"last\" required =\"required\" style=\"margin-top: 15px;margin-left: -200px;width: 200px;\" >\n");
      out.write("\t\t\t\t   \t\t</div> \n");
      out.write("\t\t\t\t   \t</td>\t\n");
      out.write("\t\t\t\t   \t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-sm-4\">\t\t\t\t \n");
      out.write("\t\t\t\t        <input   type=\"text\" placeholder=\"Email Address\" name=\"email\" required =\"required\" style=\"margin-top:1px;margin-left:-400px;width: 400px;\" >\n");
      out.write("\t\t\t\t   \t\t</div> \n");
      out.write("\t\t\t   \t\t</td>\n");
      out.write("\t\t\t   \t</tr>\n");
      out.write("\t\t\t   \t<tr>\n");
      out.write("\t\t\t   \t\t<td>\n");
      out.write("\t\t\t\t   \t\t<div class=\"col-sm-4\">\t\t\t\t \n");
      out.write("\t\t\t\t        <input   type=\"text\" placeholder=\"Password (6 or more characters)\" name=\"pass\" required =\"required\" style=\"margin-top:1px;margin-left:-400px;width: 400px;\" >\n");
      out.write("\t\t\t\t   \t\t</div>\n");
      out.write("\t\t\t   \t\t</td>\n");
      out.write("\t\t\t   \t</tr>\n");
      out.write("\t\t\t   \t<tr>\n");
      out.write("\t\t\t\t   \t<td>\n");
      out.write("\t\t\t\t   \t\t<p style=\"margin-top:1px;margin-left:-400px;width: 400px;\"> By clicking Join Now, you agree to LinkedIn's User Agreement,</br> Privacy Policy and Cookie Policy.</p>\n");
      out.write("\t\t\t\t   \t</td>\n");
      out.write("\t\t\t   \t</tr>\n");
      out.write("\t\t\t\t<tr>\t\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input class=\"submit\" type=\"submit\" value=\"Join Now\" style=\"margin-top:0px;margin-left:600px;width: 400px;height: 35px;font-weight: bold;background-color: #FFD700;border: 0 none; \"/>\n");
      out.write("\t\t\t\t\t\t<!-- <button type=\"submit\" value=\"Join Now\" style=\"margin-top:1px;margin-left: 120px;width: 400px;height: 35px;font-weight: bold;background-color: #FFD700;border: 0 none; \">Join Now </button>-->\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</table>\n");
      out.write("\t</form>\t \n");
      out.write("\t\t \t</div>\n");
      out.write("    \n");
      out.write(" </center>\n");
      out.write("<!-- <div>SignUp for New Account</div>\n");
      out.write("<form id=\"form1\" method=\"post\" action=\"signup\">\n");
      out.write("\t<div class=\"form-row\"><span class=\"label\">First Name </span><input type=\"text\" name=\"first\"/></div>\n");
      out.write("\t<div class=\"form-row\"><span class=\"label\">Last Name </span><input type=\"text\" name=\"last\"/></div>\t\n");
      out.write("\t<div class=\"form-row\"><span class=\"label\">Email </span><input type=\"email\" name=\"email\"/></div>\n");
      out.write("\t<div class=\"form-row\"><span class=\"label\">Password </span><input type=\"password\" name=\"pass\"/></div>\n");
      out.write("\t<div class=\"form-row\"><input class=\"submit\" type=\"submit\" value=\"submit\"/></div>\n");
      out.write("</form>\n");
      out.write(" -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
